### PR TITLE
Fix/zero apy

### LINKED ISSUE #205: MTA Apy not correct when rewards are not updated
**Describe the bug**
Many dials got disabled, however, the UI still shows the same APY for MTA rewards. This is because the rewards Rate does not get updated anymore. The UI has to be aware that if the last time the rewardsRate was updated longer than 7 days, the rewards are empty and no new rewards got added.

**To Reproduce**

https://mstable.app/#/mbtc/save

https://mstable.app/#/mbtc/pools

https://mstable.app/#/musd/pools

Also Single Pools Page, e.g. https://mstable.app/#/musd/pools/0x4eaa01974b6594c0ee62ffd7fee56cf11e6af936

**Expected behavior**

**Screenshots**

Screen Shot 2022-08-29 at 15 14 41

Screen Shot 2022-08-29 at 15 14 49

Screen Shot 2022-08-29 at 15 15 06

### PR DESCRIPTION
**Pull request by calvinkei**
close #205

### CODE REVIEW

**Comment by dimsome** [comment]
Can we have a small adjustment? If the APY is 0%, I don't think it makes sense to display the range, could we just change to when the APY is 0%, we display the number only, without the range?

Screen Shot 2022-08-30 at 23 11 57

**Comment by dimsome** [comment]
can we do the same for /mbtc/save page?
Screen Shot 2022-08-31 at 17 05 51

File: libs/masset-hooks/src/lib/useSelectedMassetState.tsx [hunk 1]
```diff
@@ -1,10 +1,30 @@
...
+  if (lastUpdateTime && lastUpdateTime < minLastUpdateTime) {
+    return {
+      ...mAsset,
+      savingsContracts: {
+        ...mAsset.savingsContracts,
+        v2: {
+          ...mAsset.savingsContracts.v2,
+          boostedSavingsVault: {
+            ...mAsset.savingsContracts.v2.boostedSavingsVault,
+            rewardRate: BigNumber.from(0),
```
Comment (toniocodo) [inline libs/masset-hooks/src/lib/useSelectedMassetState.tsx:23]: nit: ethers lib exposes `constants.ZERO` for this

File: apps/protocol/src/app/hooks/useFeederPoolApy.ts [hunk 2]
```diff
@@ -25,10 +25,16 @@ const useFeederPoolApyVault = (poolAddress: string, mAssetName?: MassetName) =>
 
   if (!pool || !vault || !massetPrice.value || !rewardsTokenPrice) return { fetching: true }
 
-  const rewardRateSimple = parseInt(vault.rewardRate.toString()) / 1e18
+  let rewardRateSimple = parseInt(vault.rewardRate.toString()) / 1e18
```
Comment (toniocodo) [inline apps/protocol/src/app/hooks/useFeederPoolApy.ts:28]: nit: we have `BigDecimal` helper class to help with this

File: apps/protocol/src/app/pages/Dashboard/PoolRow.tsx [hunk 3]
```diff
@@ -105,8 +105,8 @@ export const PoolRow: FC<{ feederPool: FeederPoolState; showBalance: boolean }>
           <Tooltip hideIcon tip={apyTip}>
             <CountUp end={baseApy} suffix="%" />
             <RewardsApy>
-              <CountUp end={rewardsBaseApy} prefix="+" suffix="%" />
-              &nbsp;→&nbsp;
+              {rewardsBaseApy || rewardsMaxApy ? <CountUp end={rewardsBaseApy} prefix="+" suffix="%" /> : null}
+              {rewardsBaseApy || rewardsMaxApy ? <>&nbsp;→&nbsp;</> : null}
```
Comment (toniocodo) [inline apps/protocol/src/app/pages/Dashboard/PoolRow.tsx:109]: nit: this could be put into one condition 
```
{rewardsBaseApy || rewardsMaxApy && <><CountUp end={rewardsBaseApy} prefix="+" suffix="%" />&nbsp;→&nbsp;</>}
 ```

**Review by toniocodo — APPROVED** [review]
LGTM, just a couple small nits
